### ISSUE TITLE
New version of ls_create()

### ISSUE THREAD

**Issue by jonrhodes** [sLandserve/sLandserv#2]
Laura, following my email earlier I implemented a new version of ls_create( ) on a new branch, which allows for independent control of fragmentation of supply and demand. I think it works as intended, but needs checking. It probably also has downstream consequences for the other functions since the output is slightly different (.e.g, supply and demand rasters are output as separate rasters) and I haven't looked at this yet. Also, overlapping supply and demand is possible with this way of creating the landscapes. I can look at this, but just wanted to make you aware.

**Comment by laurajanegraham** [comment]
I've checked this code through and all works as it should. I've also sorted any downstream issues. Overlapping supply/demand is fine now we generate the landscapes like this and won't cause any problems for analysis/interpretation as far as I can tell.
