### ISSUE TITLE
Issue with calculation of supply

### ISSUE THREAD

**Issue by jonrhodes** [sLandserve/sLandserv#3]
Hi Laura,

I have noticed that in the calculate_benefit() function, when there is no social-ecological network connections it escapes (lines 35 -38) and does not calculate supply. Even when there is no social-ecological network, we still need to calculate supply. I suggest this needs amending so we calculate supply even when there is no social-ecological network.

Hope this makes sense.

Cheers,

Jonathan

**Comment by laurajanegraham** [comment]
Well spotted. I've adjusted the code so that it escapes after the supply calculation and outputs the value. I'll get the simulations re-running on the HPC.
