### ISSUE TITLE
Network metrics for supply-demand network

### ISSUE THREAD

**Issue by jonrhodes** [sLandserve/sLandserv#4]
Need to check network metrics for the supply-demand bipartite networks - igraph metrics seem to be inappropriate for 2-mode bipartite networks.

**Comment by jonrhodes** [comment]
Partially fixed these metrics, but correct normalisation of centralisation measures still not properly resolved yet.

**Comment by laurajanegraham** [comment]
Fixed for degree centralization. Deleted betweenness and closeness centralization as these measures seem inappropriate for our aims - potentially need to revisit.
